config: "column"
initial_condition: "SimplePlume"
surface_setup: "DefaultMoninObukhov"
toml: [toml/single_column_precipitation_test.toml]
z_elem: 200
z_max: 10000.0
z_stretch: false
moist: "nonequil"
dt_save_to_sol: "Inf"
precip_model: "1M"
vert_diff: "FriersonDiffusion"
implicit_diffusion: true
t_end: "10days"
z_elem: 100
t_end: "10days"
dt_save_to_sol: "Inf"
dt: "15secs"
job_id: "test"
hyperdiff": nothing
